# 数据库配置
postgresql:
  dsn: "host=localhost user=postgres password=kitty dbname=agri_chain port=5432 sslmode=disable TimeZone=Asia/Shanghai"
redis:
  ip: "localhost"
  port: "6379"
key: "agricultural_chain"
