# 数据库配置
postgresql:
  dsn: "host=control_postgres user=postgres password=lwj123456 dbname=agri_chain port=5432 sslmode=disable TimeZone=Asia/Shanghai"
redis:
  ip: "control_redis"
  port: "6379"
key: "agricultural_chain"
